spring:
  datasource:
    url: jdbc:h2:mem:ticketingdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 517811

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

ticket:
  price:
    base: 5.00
    per-stop: 0.50